# This is the main configuration file for Paper.
# As you can see, there's tons to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
# 
# If you need help with the configuration or have any questions related to Paper,
# join us in our IRC channel.
# 
# IRC: #paper @ irc.spi.gt ( http://irc.spi.gt/iris/?channels=paper )
# Wiki: https://paper.readthedocs.org/ 
# Paper Forums: https://aquifermc.org/ 

verbose: false
config-version: 12
settings:
  enable-player-collisions: true
  player-auto-save-rate: -1
  load-permissions-yml-before-plugins: true
  bungee-online-mode: true
  sleep-between-chunk-saves: false
  save-empty-scoreboard-teams: false
  incoming-packet-spam-threshold: 300
  remove-invalid-statistics: false
  region-file-cache-size: 256
  min-chunk-load-threads: 2
timings:
  enabled: true
  verbose: true
  server-name-privacy: false
  hidden-config-entries:
  - database
  - settings.bungeecord-addresses
  history-interval: 300
  history-length: 3600
messages:
  kick:
    flying-player: Flying is not enabled on this server
    flying-vehicle: Flying is not enabled on this server
world-settings:
  default:
    keep-spawn-loaded-range: 8
    auto-save-interval: -1
    nether-ceiling-void-damage: false
    hopper:
      push-based: false
    use-alternate-fallingblock-onGround-detection: false
    disable-explosion-knockback: false
    elytra-hit-wall-damage: true
    grass-spread-tick-rate: 1
    enable-old-tnt-cannon-behaviors: false
    game-mechanics:
      disable-chest-cat-detection: false
      disable-end-credits: false
    allow-non-player-entities-on-scoreboards: false
    frosted-ice:
      enabled: true
      delay:
        min: 20
        max: 40
    non-player-arrow-despawn-rate: -1
    use-vanilla-world-scoreboard-name-coloring: false
    enable-treasure-maps: true
    treasure-maps-return-already-discovered: false
    save-queue-limit-for-auto-save: 50
    squid-spawn-height:
      minimum: 45.0
      maximum: 63.0
    delay-chunk-unloads-by: 10s
    max-growth-height:
      cactus: 3
      reeds: 3
    remove-corrupt-tile-entities: false
    queue-light-updates: false
    optimize-explosions: false
    use-chunk-inhabited-timer: true
    fishing-time-range:
      MinimumTicks: 100
      MaximumTicks: 600
    max-auto-save-chunks-per-tick: 24
    portal-search-radius: 128
    generator-settings:
      canyon: true
      caves: true
      dungeon: true
      fortress: true
      mineshaft: true
      monument: true
      stronghold: true
      temple: true
      village: true
      flat-bedrock: false
    allow-leashing-undead-horse: false
    mob-spawner-tick-rate: 1
    all-chunks-are-slime-chunks: false
    baby-zombie-movement-speed: 0.5
    spawner-nerfed-mobs-should-jump: false
    keep-spawn-loaded: true
    armor-stands-do-collision-entity-lookups: true
    disable-ice-and-snow: false
    skeleton-horse-thunder-spawn-chance: 0.01
    disable-thunder: false
    container-update-tick-rate: 1
    disable-teleportation-suffocation-check: false
    fire-physics-event-for-redstone: false
    despawn-ranges:
      soft: 32
      hard: 128
    falling-block-height-nerf: 0
    tnt-entity-height-nerf: 0
    filter-nbt-data-from-spawn-eggs-and-related: true
    max-entity-collisions: 8
    lava-flow-speed:
      normal: 30
      nether: 10
    water-over-lava-flow-speed: 5
    lootables:
      auto-replenish: false
      restrict-player-reloot: true
      reset-seed-on-fill: true
      max-refills: -1
      refresh-min: 12h
      refresh-max: 2d
    fast-drain:
      lava: false
      water: false
