# This is the main configuration file for Paper.
# As you can see, there's tons to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
# 
# If you need help with the configuration or have any questions related to Paper,
# join us in our Discord or IRC channel.
# 
# Discord: https://paperdiscord.emc.gs
# IRC: #paper @ irc.spi.gt ( http://irc.spi.gt/iris/?channels=paper )
# Website: https://papermc.io/ 
# Docs: https://paper.readthedocs.org/ 

verbose: false
config-version: 18
timings:
  enabled: true
  verbose: true
  server-name-privacy: false
  hidden-config-entries:
  - database
  - settings.bungeecord-addresses
  history-interval: 300
  history-length: 3600
settings:
  enable-player-collisions: true
  player-auto-save-rate: -1
  max-player-auto-save-per-tick: -1
  incoming-packet-spam-threshold: 300
  save-player-data: true
  use-versioned-world: false
  region-file-cache-size: 256
  save-empty-scoreboard-teams: false
  sleep-between-chunk-saves: false
  suggest-player-names-when-null-tab-completions: true
  queue-light-updates-max-loss: 10
  load-permissions-yml-before-plugins: true
  bungee-online-mode: true
  use-alternative-luck-formula: false
  async-chunks:
    enable: true
    generation: true
    thread-per-world-generation: true
    load-threads: -1
  spam-limiter:
    tab-spam-increment: 1
    tab-spam-limit: 500
  book-size:
    page-max: 2560
    total-multiplier: 0.98
  watchdog:
    early-warning-every: 5000
    early-warning-delay: 10000
  velocity-support:
    enabled: false
    online-mode: false
    secret: ''
messages:
  no-permission: '&cI''m sorry, but you do not have permission to perform this command.
    Please contact the server administrators if you believe that this is in error.'
  kick:
    flying-player: Flying is not enabled on this server
    flying-vehicle: Flying is not enabled on this server
    connection-throttle: Connection throttled! Please wait before reconnecting.
    authentication-servers-down: ''
world-settings:
  default:
    keep-spawn-loaded: true
    keep-spawn-loaded-range: 8
    auto-save-interval: -1
    skip-entity-ticking-in-chunks-scheduled-for-unload: true
    disable-thunder: false
    disable-ice-and-snow: false
    skeleton-horse-thunder-spawn-chance: 0.01
    armor-stands-do-collision-entity-lookups: true
    enable-treasure-maps: true
    treasure-maps-return-already-discovered: false
    fire-physics-event-for-redstone: false
    use-vanilla-world-scoreboard-name-coloring: false
    disable-teleportation-suffocation-check: false
    disable-creeper-lingering-effect: false
    prevent-moving-into-unloaded-chunks: false
    allow-non-player-entities-on-scoreboards: false
    nether-ceiling-void-damage-height: 0
    grass-spread-tick-rate: 1
    water-over-lava-flow-speed: 5
    bed-search-radius: 1
    use-faster-eigencraft-redstone: false
    container-update-tick-rate: 1
    parrots-are-unaffected-by-player-movement: false
    disable-explosion-knockback: false
    non-player-arrow-despawn-rate: -1
    creative-arrow-despawn-rate: -1
    prevent-tnt-from-moving-in-water: false
    portal-search-radius: 128
    count-all-mobs-for-spawning: false
    save-queue-limit-for-auto-save: 50
    fixed-chunk-inhabited-time: -1
    max-chunk-sends-per-tick: 81
    queue-light-updates: false
    remove-corrupt-tile-entities: false
    max-auto-save-chunks-per-tick: 24
    max-chunk-gens-per-tick: 10
    experience-merge-max-value: -1
    optimize-explosions: false
    delay-chunk-unloads-by: 10s
    filter-nbt-data-from-spawn-eggs-and-related: true
    falling-block-height-nerf: 0
    tnt-entity-height-nerf: 0
    max-entity-collisions: 8
    duplicate-uuid-resolver: saferegen
    duplicate-uuid-saferegen-delete-range: 32
    armor-stands-tick: true
    spawner-nerfed-mobs-should-jump: false
    allow-leashing-undead-horse: false
    baby-zombie-movement-speed: 0.5
    all-chunks-are-slime-chunks: false
    mob-spawner-tick-rate: 1
    anti-xray:
      enabled: false
      engine-mode: 1
      chunk-edge-mode: 2
      max-chunk-section-index: 3
      update-radius: 2
      hidden-blocks:
      - gold_ore
      - iron_ore
      - coal_ore
      - lapis_ore
      - mossy_cobblestone
      - obsidian
      - chest
      - diamond_ore
      - redstone_ore
      - lit_redstone_ore
      - clay
      - emerald_ore
      - ender_chest
      replacement-blocks:
      - stone
      - planks
    lightning-strike-distance-limit:
      sound: -1
      impact-sound: -1
      flash: -1
    game-mechanics:
      disable-chest-cat-detection: false
      disable-end-credits: false
      disable-player-crits: false
      shield-blocking-delay: 5
      disable-sprint-interruption-on-attack: false
      disable-relative-projectile-velocity: false
      villages-load-chunks: false
      scan-for-legacy-ender-dragon: true
      disable-unloaded-chunk-enderpearl-exploit: true
    max-growth-height:
      cactus: 3
      reeds: 3
    despawn-ranges:
      soft: 32
      hard: 128
    hopper:
      cooldown-when-full: true
      disable-move-event: false
    fishing-time-range:
      MinimumTicks: 100
      MaximumTicks: 600
    lootables:
      auto-replenish: false
      restrict-player-reloot: true
      reset-seed-on-fill: true
      max-refills: -1
      refresh-min: 12h
      refresh-max: 2d
    frosted-ice:
      enabled: true
      delay:
        min: 20
        max: 40
    squid-spawn-height:
      maximum: 0.0
