# This is the main configuration file for PaperSpigot.
# As you can see, there's tons to configure. Some options may impact gameplay, so use
# with caution, and make sure you know what each option does before configuring.
# 
# If you need help with the configuration or have any questions related to PaperSpigot,
# join us at the IRC.
# 
# IRC: #paperspigot @ irc.spi.gt ( http://irc.spi.gt/iris/?channels=PaperSpigot )

config-version: 9
data-value-allowed-items: []
settings:
  limit-player-interactions: true
  baby-zombie-movement-speed: 0.5
effect-modifiers:
  strength: 1.3
  weakness: -0.5
warnWhenSettingExcessiveVelocity: true
stackable-buckets:
  lava: false
  water: false
  milk: false
world-settings:
  default:
    verbose: true
    disable-explosion-knockback: false
    water-over-lava-flow-speed: 5
    tnt-entity-height-nerf: 0
    use-hopper-check: false
    fast-drain:
      lava: false
      water: false
    load-chunks:
      enderpearls: false
      tnt-entities: false
      falling-blocks: false
    lava-flow-speed:
      normal: 30
      nether: 10
    tnt-explosion-volume: 4.0
    falling-block-height-nerf: 0
    squid-spawn-height:
      minimum: 45.0
      maximum: 63.0
    optimize-explosions: false
    max-growth-height:
      cactus: 3
      reeds: 3
    game-mechanics:
      boats-drop-boats: false
      disable-player-crits: false
      disable-chest-cat-detection: false
      disable-end-credits: false
    mob-spawner-tick-rate: 1
    cache-chunk-maps: false
    fishing-time-range:
      MinimumTicks: 100
      MaximumTicks: 900
    despawn-ranges:
      soft: 32
      hard: 128
    nether-ceiling-void-damage: false
    player-exhaustion:
      block-break: 0.02500000037252903
      swimming: 0.014999999664723873
    remove-invalid-mob-spawner-tile-entities: true
    remove-unloaded:
      enderpearls: true
      tnt-entities: true
      falling-blocks: true
    fix-cannons: false
    allow-block-location-tab-completion: true
    generator-settings:
      canyon: true
      caves: true
      dungeon: true
      fortress: true
      mineshaft: true
      monument: true
      stronghold: true
      temple: true
      village: true
      flat-bedrock: false
    falling-blocks-collide-with-signs: false
    container-update-tick-rate: 1
    keep-spawn-loaded: true
    portal-search-radius: 128
    disable-mood-sounds: false
    use-async-lighting: false
    disable-ice-and-snow: false
    tick-next-tick-list-cap: 10000
    tick-next-tick-list-cap-ignores-redstone: false
    disable-thunder: false
    allow-undead-horse-leashing: false
    all-chunks-are-slime-chunks: false
    disable-teleportation-suffocation-check: false
    player-blocking-damage-multiplier: 0.5
